export const FIELD = {
  WIDTH: 74,
  HEIGHT: 111,
  COLOR: "#00a000",
};

export const MARKUP_OFFSET = 3;

export const MARKUP = {
  SETTINGS: {
    LINE_WIDTH: 0.5,
    DOT_RADIUS: 0.75,
    CENTRAL_CIRCLE_RADIUS: 9.15,
    COLOR: "#fff",
    FILL: "none",
    CIRCLE_LINE_WIDTH: "none",
    RELATIVE_LEFT_MOST_X: 0,
  },
  DIMENSIONS: {
    WIDTH: FIELD.WIDTH - 2 * MARKUP_OFFSET,
    HALF_WIDTH: (FIELD.WIDTH - 2 * MARKUP_OFFSET) / 2,
    HEIGHT: FIELD.HEIGHT - 2 * MARKUP_OFFSET,
    HALF_HEIGHT: (FIELD.HEIGHT - 2 * MARKUP_OFFSET) / 2,
    ONE_THIRD_HEIGHT: (FIELD.HEIGHT - 2 * MARKUP_OFFSET) / 3,
    TWO_THIRDS_HEIGHT: ((FIELD.HEIGHT - 2 * MARKUP_OFFSET) / 3) * 2,
  }
};

export const LINES = {
  DEFENCE: {
    X: 0,
    Y: MARKUP.DIMENSIONS.TWO_THIRDS_HEIGHT,
  },
  CENTER: {
    X: 0,
    Y: MARKUP.DIMENSIONS.HALF_HEIGHT,
  },
  OFFENCE: {
    X: 0,
    Y: MARKUP.DIMENSIONS.ONE_THIRD_HEIGHT,
  },
  DASH_LENGTH: 2,
  DASH_GAP: 1,
};

export const GOAL_AREA = {
  X: 24.84,
  Y: 0,
  HEIGHT: 5.5,
  WIDTH: 18.32,
};

const PENALTY_AREA_HEIGHT = 16.5;

export const PENALTY_AREA = {
  X: 13.84,
  Y: 0,
  HEIGHT: PENALTY_AREA_HEIGHT,
  WIDTH: 40.32,
  MARK_Y: 10.94,
  ARC: {
    START_X: 26.733027,
    START_Y: PENALTY_AREA_HEIGHT,
    END_X: 14.533946,
    END_Y: 0,
    RADIUS: MARKUP.SETTINGS.CENTRAL_CIRCLE_RADIUS,
  }
};
