import * as FC from './fieldConstants';

type SupportedRadius = 3 | 4 | 5

type RadiusMultiplierMap = {
  [key in SupportedRadius]: {
    CENTER_DOTS_MULTIPLIER_Y: number;
    SIDE_DOTS_MULTIPLIER_X: number;
    SIDE_DOTS_MULTIPLIER_Y: number;
    TEXT_SIZE: number;
  };
}

const MULTIPLIERS_MAP: RadiusMultiplierMap = {
  3: {
    CENTER_DOTS_MULTIPLIER_Y: 8,
    SIDE_DOTS_MULTIPLIER_X: 7,
    SIDE_DOTS_MULTIPLIER_Y: 2.5,
    TEXT_SIZE: 2.4,
  },
  4: {
    CENTER_DOTS_MULTIPLIER_Y: 5.65,
    SIDE_DOTS_MULTIPLIER_X: 5,
    SIDE_DOTS_MULTIPLIER_Y: 2,
    TEXT_SIZE: 2.9,
  },
  5: {
    CENTER_DOTS_MULTIPLIER_Y: 4.2,
    SIDE_DOTS_MULTIPLIER_X: 4,
    SIDE_DOTS_MULTIPLIER_Y: 1.5,
    TEXT_SIZE: 3.8,
  },
}

export const MARK_FILL_COLOR = "#fff";
export const MARK_RADIUS: SupportedRadius = 5;
export const MARK_TEXT_COLOR = "#000";
export const MARK_TEXT_SIZE = `${MULTIPLIERS_MAP[MARK_RADIUS].TEXT_SIZE}px`;

const CENTER_DOTS_OFFSET_Y = MARK_RADIUS * MULTIPLIERS_MAP[MARK_RADIUS].CENTER_DOTS_MULTIPLIER_Y;
const SIDE_DOTS_OFFSET_X = MARK_RADIUS * MULTIPLIERS_MAP[MARK_RADIUS].SIDE_DOTS_MULTIPLIER_X;
const SIDE_DOTS_OFFSET_Y = MARK_RADIUS * MULTIPLIERS_MAP[MARK_RADIUS].SIDE_DOTS_MULTIPLIER_Y;

const BASE_HALF_X = FC.MARKUP.DIMENSIONS.HALF_WIDTH - MARK_RADIUS;
const BASE_DEFENCE_Y = FC.LINES.DEFENCE.Y - MARK_RADIUS;
const BASE_OFFENCE_Y = FC.LINES.OFFENCE.Y - MARK_RADIUS;
const BASE_MIDFIELD_Y = FC.LINES.CENTER.Y - MARK_RADIUS;

export const GOALKEEPER = {
  X: BASE_HALF_X,
  Y: FC.MARKUP.DIMENSIONS.HEIGHT - (FC.GOAL_AREA.HEIGHT / 2) - MARK_RADIUS,
};

export const THIRDS_CENTER_DOTS = {
  X: BASE_HALF_X,
  BACK_Y: BASE_DEFENCE_Y + CENTER_DOTS_OFFSET_Y,
  FORWARD_Y: BASE_OFFENCE_Y - CENTER_DOTS_OFFSET_Y,
};

export const MIDFIELD_DOTS = {
  X: BASE_HALF_X,
  DEFENCE_Y: BASE_DEFENCE_Y,
  MIDFIELD_Y: BASE_MIDFIELD_Y,
  ATTACK_Y: BASE_OFFENCE_Y,
};

export const SIDE_DOTS = {
  LEFT_X: BASE_HALF_X - SIDE_DOTS_OFFSET_X,
  RIGHT_X: BASE_HALF_X + SIDE_DOTS_OFFSET_X,
  BACK_Y: BASE_DEFENCE_Y + SIDE_DOTS_OFFSET_Y,
  FORWARD_Y: BASE_OFFENCE_Y - SIDE_DOTS_OFFSET_Y,
}
