import * as FC from './fieldConstants';

export const BASE_MARK_SIZE = 2;
export const THIRDS_LINES_OFFSET_Y = BASE_MARK_SIZE * 4;
export const CENTER_LINE_OFFSET_Y = BASE_MARK_SIZE * 1.75;
export const SIDE_DOTS_LINE_OFFSET = BASE_MARK_SIZE * 4;

export const DIMENSIONS = {
  CIRCLE: {
    RADIUS: BASE_MARK_SIZE,
  },
  RECTANGLE: {
    HORIZONTAL: {
      SHORT: {
        WIDTH: BASE_MARK_SIZE * 14,
        HEIGHT: BASE_MARK_SIZE * 2,
      },
      LONG: {
        WIDTH: BASE_MARK_SIZE * 19,
        HEIGHT: BASE_MARK_SIZE * 2,
      },
    },
    VERTICAL: {
      WIDTH: BASE_MARK_SIZE * 2,
      HEIGHT: BASE_MARK_SIZE * 13,
    },
  },
};

export const GOALKEEPER = {
  X: FC.MARKUP.DIMENSIONS.HALF_WIDTH - DIMENSIONS.CIRCLE.RADIUS,
  Y: FC.MARKUP.DIMENSIONS.HEIGHT - (FC.GOAL_AREA.HEIGHT / 2) - DIMENSIONS.CIRCLE.RADIUS,
};

export const LEFT_VERTICAL_MARKERS = {
  X: FC.MARKUP.SETTINGS.RELATIVE_LEFT_MOST_X - DIMENSIONS.CIRCLE.RADIUS,
  DEFENCE_Y: (FC.MARKUP.DIMENSIONS.HEIGHT + FC.LINES.DEFENCE.Y - DIMENSIONS.RECTANGLE.VERTICAL.HEIGHT) / 2,
  MIDFIELD_Y: (FC.LINES.DEFENCE.Y + FC.LINES.OFFENCE.Y - DIMENSIONS.RECTANGLE.VERTICAL.HEIGHT) / 2,
  OFFENCE_Y: (FC.LINES.OFFENCE.Y - DIMENSIONS.RECTANGLE.VERTICAL.HEIGHT) / 2,
};

export const THIRDS_CENTER_LINES = {
  X: (FC.MARKUP.DIMENSIONS.WIDTH - DIMENSIONS.RECTANGLE.HORIZONTAL.SHORT.WIDTH) / 2,
  BACK_Y: FC.LINES.DEFENCE.Y - DIMENSIONS.CIRCLE.RADIUS + THIRDS_LINES_OFFSET_Y,
  FORWARD_Y: FC.LINES.OFFENCE.Y - DIMENSIONS.CIRCLE.RADIUS - THIRDS_LINES_OFFSET_Y,
};

export const CENTER_LINES = {
  X: (FC.MARKUP.DIMENSIONS.WIDTH - DIMENSIONS.RECTANGLE.HORIZONTAL.LONG.WIDTH) / 2,
  DEFENCE_Y: FC.LINES.CENTER.Y - DIMENSIONS.CIRCLE.RADIUS + FC.MARKUP.SETTINGS.CENTRAL_CIRCLE_RADIUS + CENTER_LINE_OFFSET_Y,
  MIDFIELD_Y: FC.LINES.CENTER.Y - DIMENSIONS.CIRCLE.RADIUS,
  ATTACK_Y: FC.LINES.CENTER.Y - DIMENSIONS.CIRCLE.RADIUS - FC.MARKUP.SETTINGS.CENTRAL_CIRCLE_RADIUS - CENTER_LINE_OFFSET_Y,
};

export const SIDE_DOTS = {
  LEFT_X: (FC.MARKUP.DIMENSIONS.WIDTH - DIMENSIONS.RECTANGLE.HORIZONTAL.SHORT.WIDTH) / 2 - DIMENSIONS.CIRCLE.RADIUS - SIDE_DOTS_LINE_OFFSET,
  RIGHT_X: (FC.MARKUP.DIMENSIONS.WIDTH + DIMENSIONS.RECTANGLE.HORIZONTAL.SHORT.WIDTH) / 2 - DIMENSIONS.CIRCLE.RADIUS + SIDE_DOTS_LINE_OFFSET,
}
